### ISSUE TITLE
Default file logging

### ISSUE THREAD

**Issue by timkung** [silverstripe/silverstripe-saml#10] opened 2018-04-09 03:00 UTC
At the moment in the 4.0 branch (and also in the 3.0 branch), by default there is no file logging setup. Currently the `framework/_config/logging.yml` file is setup to use just the `SilverStripe\Logging\HTTPOutputHandler` which would mean any errors logged in this module just display in the browser.

It would be good to potentially add a file logging handler that is added to the logger interface to write any errors to a file (which could default to syslog for example), to ensure all errors are logged by default.

**Comment by madmatt** [comment] 2018-11-06 09:03
Hrm, I'm not sure this is something that the module should configure - instead, we should leave this to either platform-specific code (e.g. CWP includes [this logging config](https://github.com/silverstripe/cwp-core/blob/master/_config/logging.yml)), or website-specific code (e.g. to forward errors to a error monitoring service like Raygun.io or Papertrail.

@robbieaverill thoughts?

**Comment by NightJar** [comment] 2018-11-06 09:14
I think that so long as there is logging information _generated_ by this module, then it's up to the configuration of the project on how to deal with that information.

I inspected and thought about closing this earlier on the same basis you raise @madmatt - but what I'm unsure of is whether or not this module generates anything useful _to_ log. If not then at least that should be addressed.

**Comment by robbieaverill** [comment] 2018-11-06 09:18
If I understand correctly, the problem is that errors logged from this module are displayed in the browser, or swallowed up by the SilverStripe error handler.

I think the problem here is a manifestation of https://github.com/silverstripe/silverstripe-framework/issues/8044, which has an open pull request to separate the default log handler from the core SilverStripe error handlers. I'm going to close this for now, because fixing that issue will also fix this issue.

**Closed as completed by robbieaverill** 2018-11-06 09:18 UTC
Labels: type/enhancement, affects/v4, change/minor, effort/easy, impact/low

**Comment by madmatt** [comment] 2018-11-06 10:44
The most important part of the module to have logging has it, which is the SAML response parsing (https://github.com/silverstripe/silverstripe-saml/blob/master/src/Control/SAMLController.php#L97) so I'm happy with this being closed now that the module does actually log that info. Feel free to re-open if there's specific stuff that's missing from the logs @timkung.
